When using RxGORM each entity that you submit to a REST service is known as a domain class.

If you are using RxGORM within Grails you can create a domain class with the `create-domain-class` command provided by the command line. Alternatively if you are not using Grails simply creating a Groovy class with `src/main/groovy` of your project will suffice.

A RxGORM for REST domain class must as a minimum implement the link:../api/grails/gorm/rx/rest/RxRestEntity.html[RxRestEntity] trait. For example:

[source,groovy]
----
package example

import grails.gorm.rx.rest.*

class Book implements RxRestEntity<Book> {
    String title
}
----

If you are not using Grails and have placed the domain class in `src/main/groovy` you must also annotate the domain class with the `Entity` annotation:

[source,groovy]
----
...
import grails.gorm.annotation.*

@Entity
class Book implements RxRestEntity<Book> {
    ...
}
----

NOTE: The type is provided as a generic argument to the `RxRestEntity` trait. This is important to ensure the correct return signatures are produced for methods provided by the trait.

For more information on domain modelling in GORM, take a look at the http://docs.grails.org/latest/guide/GORM.html#domainClasses[GORM user guide documentation] on the subject.
