[[configOptions]]
==== Configuration Options

The following configuration options are available:

* `grails.gorm.rest.host` - The default host to connect to
* `grails.gorm.rest.hosts` - The hosts to connect to in a load balanced configuration
* `grails.gorm.rest.charset` - The character encoding to use
* `grails.gorm.rest.readTimeout - The default read timeout
* `grails.gorm.rest.logLevel` -  The default wire log level
* `grails.gorm.rest.updateMethod` - The default HTTP method to use for updates. Defaults to PUT
* `grails.gorm.rest.pool.options` - The configuration options to create the https://github.com/ReactiveX/RxNetty/blob/0.5.x/rxnetty-common/src/main/java/io/reactivex/netty/client/pool/PoolConfig.java[io.reactivex.netty.client.pool.PoolConfig] with (only applicable to single host configurations).
* `grails.gorm.rest.username` - The username to ues for BASIC auth
* `grails.gorm.rest.password` - The password to use for BASIC auth
* `grails.gorm.rest.interceptors` - The link:../api/org/grails/datastore/rx/rest/interceptor/RequestInterceptor.html[RequestInterceptor] instances to use
* `grails.gorm.rest.query.type` - The type of query implementation to use. Either "simple" or "bson"
* `grails.gorm.rest.parameters.order` - The name of the parameter used to send the order (descending or ascending) to the server
* `grails.gorm.rest.parameters.expand` - The name of the parameter used to expand nested resources
* `grails.gorm.rest.parameters.sort` - The name of the parameter used to send the property to sort by to the server
* `grails.gorm.rest.parameters.max` - The name of the parameter used to send to restrict the maximum number of results
* `grails.gorm.rest.parameters.offset` - The name of the parameter used to send to provide the offset for pagination
* `grails.gorm.rest.parameters.query` - The name of the parameter used to send the query when using "bson" query type
